name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "students"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres_sorteador_db:5432/students"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_sorteador_app npm run test